name: Generate Go Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install Protocol Buffers Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protocol Buffers Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Go code
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          mkdir -p gen/go
          protoc -I proto proto/sso/*.proto \
            --go_out=./gen/go/ --go_opt=paths=source_relative \
            --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
        shell: bash

      - name: Commit and Push Generated Code
        run: |
          git add gen/go
          git commit -m "Auto-generate Go code"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
